version: '3.8'
services:
  netbox_yaml_generator:
    build: .
    container_name: netbox-yaml-generator
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./output:/app/output
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped